name = "personal-website"
compatibility_date = "2026-02-11"
compatibility_flags = ["nodejs_compat"]
main = "@tanstack/react-start/server-entry"

routes = [
  { pattern = "devlomingo.com", custom_domain = true },
  { pattern = "www.devlomingo.com", custom_domain = true },
]

[observability]
enabled = true
